export { createRenderer } from './renderer'
export { renderSlot } from './helpers/renderSlot'
export { createTextVnode } from './vnode'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { h } from './h'
